### ISSUE TITLE
Release:

### ISSUE THREAD

**Issue by Limlay** [prisma/docs#1838]
## Release

- [ ] Merge in new content
- [ ] Update 'What's new' page with links to the relase notes and new docs (example: https://www.prisma.io/docs/about/whats-new-in-prisma-docs#april-04-2021)
- [ ] Add links to release notes

## After release

- [ ] Add the 'What's new' video 
- [ ] Clean up milestone

**Comment by mhwelander** [comment]
Accidental ticket?
