### ISSUE TITLE
Add guidance to Data Proxy doc about location choice

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/docs#3245]
Suggestion from Jan

Early in the [Data Proxy doc](https://www.prisma.io/docs/concepts/data-platform/data-proxy), we talk about the Data Proxy location. Perhaps we need some guidance here for the user. How do they choose the location? Should it be close to their database server or to their application server? Or something else? What are the considerations? We could either explain here (if brief) or (if longer) link to this information elsewhere (in this doc or in another doc).

**Comment by tanberry** [comment]
@Zach will handle this in the new docs about creating new Projects; he will discuss how to select the most appropriate cluster (which is where the DP goes).
