### ISSUE TITLE
Gatsby does not seem to respect <img width=""> attribute with local image files

### ISSUE THREAD

**Issue by zachtil** [prisma/docs#4235]
**!URGENT!** This impacts migration from Cloudinary!

When using the `<img>` component with image URLs from Cloudinary, Gatsby respects the provided @width attribute.

When using `<img>` component with local images, Gatsby ignores the @width attribute and serves the image at full width.

**Example component**

<img width="894" alt="img-comp-local-image-width" src="https://user-images.githubusercontent.com/103522279/206777610-dc7d1841-1900-4089-909c-7c598950c4c1.png">

**Example output with local file**
<img width="693" alt="local-file-full-width-output" src="https://user-images.githubusercontent.com/103522279/206777905-5e33c164-6d72-4686-b7e3-54825ab33896.png">

**Example output with Cloudinary link**
<img width="742" alt="cloudinary-file-width-output" src="https://user-images.githubusercontent.com/103522279/206779555-81d5869a-21f5-4be5-a68e-52173576298e.png">

**Comment by zachtil** [comment]
The <img> elements generated for Cloudinary and the ones from local image files are quite different. In the local file case, it seems to be a processing made by the gatsby-sharp-plugin.

`<img src="https://res.cloudinary.com/prismaio/image/upload/v1666365936/docs/pdp/manage-project-members/manage-project-members-01-open-project-settings_cptcki.png" alt="Prisma Data Platform - Edit project settings - Change the project name and the project URL handle" width="350px">`

`<img class="gatsby-resp-image-image" alt="Prisma Data Platform - Create project - Paste database connection string, select Data Proxy region, enable static IPs" title="Prisma Data Platform - Create project - Paste database connection string, select Data Proxy region, enable static IPs" src="/static/f213a66a58f6b560f353fa7a8881962f/a6d36/create-project-01-paste-connection-string.png" srcset="/static/f213a66a58f6b560f353fa7a8881962f/222b7/create-project-01-paste-connection-string.png 163w,/static/f213a66a58f6b560f353fa7a8881962f/ff46a/create-project-01-paste-connection-string.png 325w,/static/f213a66a58f6b560f353fa7a8881962f/a6d36/create-project-01-paste-connection-string.png 650w,/static/f213a66a58f6b560f353fa7a8881962f/e548f/create-project-01-paste-connection-string.png 975w,/static/f213a66a58f6b560f353fa7a8881962f/3c492/create-project-01-paste-connection-string.png 1300w,/static/f213a66a58f6b560f353fa7a8881962f/701e9/create-project-01-paste-connection-string.png 1780w" sizes="(max-width: 650px) 100vw, 650px" loading="lazy" decoding="async" style="width: 100%; height: 100%; margin: 0px; vertical-align: middle; position: absolute; top: 0px; left: 0px; opacity: 1; transition: opacity 0.5s ease 0s; color: inherit; box-shadow: white 0px 0px 0px 400px inset;">
`

**Comment by nilubava** [comment]
@zachtil For the images placed inside `/content/doc-images`, `gatsby-remark-images` adds this particular wrapper to make them responsive. If we remove this plugin, all the local images will lose the responsiveness. But for you to bypass this plugin altogether, the best solution would be to keep them inside the `static` folder as shown in this [PR](https://github.com/prisma/docs/pull/4242/files) example. 

Does this seem like an ideal solution for your use case?

**Comment by zachtil** [comment]
Hey @nilubava. Is this something we will need to do for all images or only for the images that need to be specified a `max-width` / `width` attribute?

**Comment by nilubava** [comment]
This is only for those images you need to have with a specific width (or bypass the `gatsby` plugin, basically)

**Comment by zachtil** [comment]
@nilubava I've tried this here, but am not sure what is broken as it does not seem to work:

https://github.com/prisma/docs/pull/4254/files#diff-8092a58a009245f984e75a303f815bd5027296964fa75bf2f71fc1dc2381f349

**Comment by zachtil** [comment]
I've actually made it work now.

I wonder if this `src` relies on the file / folder structure in the build (which I am not familiar with) rather than what we see when we work with files.

**Comment by nilubava** [comment]
Sorry, I did not understand what you meant. `static` folder contains the assets which are static and since they are not covered by the plugin, then it is available for us to customise with properties

**Comment by zachtil** [comment]
@nilubava here's where the confusion comes from:

## Referencing image files from MDX files in development environment

In the dev environment, I've tried referencing an image from `/content/800-data-platform/400-members/100-add.mdx` to `/static/images/team-members-invite-and-select-role.png`.

I've used this path: `../../../static/images/team-members-invite-and-select-role.png`

It did not feel right but I did not know how to reference the image. When `npm run dev` runs, I am not able to see the image in the local build.

## Referencing image files from generated html files in Gatsby build

Since that, I've realized that the path you suggest is not based on the development environment, but it is probably based on the produced build of `npm run build` which if I understand correctly is generated in the `public/` folder.

This is the first time I've had to figure out how the Gatsby build is structured. So with that, looking at the generated files, I am finding these:

`public/data-platform/members/add/index.html`
`public/images/team-members-invite-and-select-role.png`

But even with these, the correct path should be:

`../../../images/team-members-invite-and-select-role.png`

Which also does not work in the context of `npm run build` and opening `http://localhost:8000/data-platform/members/add`.

## URL path seems to be defining factor for images references to the `static/` folder

I've just tried locally again with `npm run dev` the path `../../images/team-members-invite-and-select-role.png` and works just fine now.

And I am also now realizing why that is:

The URL I open is `http://localhost:8000/data-platform/members/add`, without a `/` in the end, in which case the path `../../images/team-members-invite-and-select-role.png` works and the image is displayed.

However, if I go to `http://localhost:8000/data-platform/members/add/`, the image is no longer displayed. 

## Conclusions

1. The process for adding images to `static/` feels a bit difficult to understand on how the correct path works. You have to know the generated Gatsby build file and folder structure to understand that.
2. Even with image files in `static/`, showing them in different URL patterns seems to break. Depending on the URL pattern and the image file path, the image may or may not appear as expected.

### Example 1

**Image file path**
`../../../images/team-members-invite-and-select-role.png`
**Appears correctly in**
`http://localhost:8000/data-platform/members/add/`
**Does not appear in**
`http://localhost:8000/data-platform/members/add`

### Example 2

**Image file path**
`../../images/team-members-invite-and-select-role.png`
**Appears correctly in**
`http://localhost:8000/data-platform/members/add`
**Does not appear in**
`http://localhost:8000/data-platform/members/add/`

**Comment by zachtil** [comment]
Had a chat with @nilubava today and we'll check if it is possible to enable the `max-width` attribute in the `<img>` component and whether the Gatsby image plugin will be able to respect that for individual images.

**Comment by nilubava** [comment]
So here are my findings:
Our local images are wrapped by the plugin gatsby-remark-images which does not let us specify max-width for individual images, and only has an option maxWidth for all the images in the content folder.
Upon digging deeper, I found another community member submitted plugin called `@bonobolabs/gatsby-remark-images-custom-widths` (https://www.gatsbyjs.com/plugins/@bonobolabs/gatsby-remark-images-custom-widths/) which is exactly what we need.  This plugin lets us specify the width attribute for each image like so :
```
<img
  src="../../doc-images/..."
  width="375px"
  alt="..."
/>
```

It renders the image like below:
<img width="1107" alt="Screenshot 2022-12-15 at 15 41 49" src="https://user-images.githubusercontent.com/8801572/207891888-1eb8a91d-57c7-4a6b-a384-60b7a95f2bea.png">

Now, the difference between cloudinary images and this one is that these images are centrally aligned and the cloudinary ones are left aligned.
See this:

<img width="845" alt="Screenshot 2022-12-15 at 15 43 56" src="https://user-images.githubusercontent.com/8801572/207891971-fbaa46fc-4129-4230-8c3c-8316f35cadce.png">

Is this an issue? Do you need strictly left aligned images ?
 If so, we have 2 options:
Tougher solution - Create a new custom plugin like the one above (`@bonobolabs/gatsby-remark-images-custom-widths`) which lets us customise width and alignment
Easier solution - Change all images served by the plugin to be left aligned (this can be done using a generic class) This means all images from '/doc-images' will be left aligned
What do you think is good for your situation?

**Comment by zachtil** [comment]
Thank you @nilubava 🎉  The `width` attribute is now respected and will help me resolve the Cloudinary issues.
