### ISSUE TITLE
No `every` example (shows `some` instead, plus typo in wrong example)

### ISSUE THREAD

**Issue by janpio** [prisma/docs#5116]
Our every example is actually for some and has a typo: 
https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#get-all-user-records-where-all-posts-are-published-and-a-least-one-related-post-mentions-prisma

**Comment by ruheni** [comment]
The `every` and `some` examples have been reused, and I think, in this case, we could cut on the scope for the example snippets.
